### ISSUE TITLE
Notifications on Android Wear show a solid color as background

### ISSUE THREAD

**Issue by Darkwater** [Pushjet/Pushjet-Android#1]
When I receive a notification on my Wear 5.0.2 watch, the background for the notification card is solid blue.

**Comment by Mechazawa** [comment]
Can you provide a picture of the issue and the name/brand of your smartwatch? Because it works on my device™.

**Comment by Darkwater** [comment]
[It doesn't work™](!http://novaember.com/s/573172487.png)

It's an ASUS ZenWatch running Wear 5.0.2, and my OnePlus One is running on a CM12.1 nightly which is based on 5.1.1.

**Comment by Mechazawa** [comment]
[This video][1] (really old build) should show what should be happening. Android wear should only use the solid color when preparing the background. Could you provide me with some logcat logs of when it happens? I have a weird feeling that it has to do with the icon cache code.

[1]: http://a.pomf.se/bjfhge.webm

**Comment by Darkwater** [comment]
I/GCM     ( 2740): GCM message io.Pushjet.api 0:1430595031220303%061aec03f9fd7ecd
    D/ZenLog  (  939): disable_effects: 0|io.Pushjet.api|3|null|10150,listenerHints
    D/HeadsetStateMachine( 3671): Disconnected process message: 10, size: 0
    D/Ulp_jni (  939): Location CB invoked

That's all I see on the phone. Doesn't look like it's generating any log messages on my wearable.

**Comment by Darkwater** [comment]
Actually, I saw this when I tried again after restarting my watch, might be coincidence, though:

    V/wearable(  663): ensureBuffersHaveSpace: increasing size from 2807 to 3801
    I/art     (  609): Background sticky concurrent mark sweep GC freed 7215(320KB) AllocSpace objects, 5(84KB) LOS objects, 1% free, 13MB/14MB, paused 12.616ms total 86.440ms
    I/art     (  609): Background partial concurrent mark sweep GC freed 5493(346KB) AllocSpace objects, 7(2MB) LOS objects, 14% free, 11MB/13MB, paused 2.600ms total 116.458ms

**Comment by Darkwater** [comment]
I made a new service and subscribed to it, that service's icon shows up now.
