### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by Asara** [Pushjet/Pushjet-Android#23]
Pushjet would be a great addition to F-droid.  It would make it easier to keep it updated etc, as well as drive more users to find out about Pushjet itself.

**Comment by Bubu** [comment]
Cannot be done as long as this requires gcm/fcm.

**Comment by dessalines** [comment]
Can those be removed? If this is really foss, it should work w/o them.

**Comment by Asara** [comment]
Devs would have to implement websockets to do this, which is a non-trivial amount of work.  I can see why it isn't a priority, and don't fault the devs for this.

I don't have GCM on my phone however, so I'm still unable to use pushjet sadly.
