### ISSUE TITLE
PushJet server issue https://api.pushjet.io/message all ways returns error 500

### ISSUE THREAD

**Issue by ChristBE** [Pushjet/Pushjet-Android#30]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by AJOnlineServices** [comment]
I've already posted about this but I think taht I have been told that the issue cannot be replicated.
It appears to only happen once a device (in my case, an Android device) subscribes to the service.

**Comment by ChristBE** [comment]
added another android device still getting error 500
deleted on all device still error 500
added a device again still error 500
this must be a server problem

**Comment by ChristBE** [comment]
Did test by "Subscribe to a service" via web page, send a message got ERROR 500
but via web page "Fetch unread messages"  I was able to get the message just send.
so ERROR 500 must come from "Google Cloud Messaging" call on the server I guess

**Comment by ChristBE** [comment]
removed all android subscriptions and no more ERROR 500 when a message is send.
 so ERROR 500 points again to "Google Cloud Messaging" call on the server I guess

**Comment by Mechazawa** [comment]
Sorry about that, I don't have the time to maintain this project anymore and it kinda slipped through the cracks. I've fixed the issue. It had to do with a misconfigured server with some outdated packages that were causing issues. 

It should be fixed. I'll close this issue, please remake one when this happens again.
